version: "2"

services:
  worker:
    environment:
      - REDIS_HOST
      - PG_HOST
    build:
      context: ./worker
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
